name: Build & Push Backend to GCP Artifact Registry

on:
  push:
    branches: [ main, staging ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Authenticate to GCP using Workload Identity Federation
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/1058846922605/locations/global/workloadIdentityPools/stg-backend-github-ci-pool/providers/stg-backend-repo
          service_account: stg-backend-github-ci@peak-nimbus-466309-n1.iam.gserviceaccount.com
        
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker to use gcloud auth
        run: |
          gcloud auth configure-docker asia-east1-docker.pkg.dev

      - name: Build and push Docker image to Artifact Registry
        run: |
          COMMIT_SHA=${{ github.sha }}
          IMAGE_NAME=asia-east1-docker.pkg.dev/peak-nimbus-466309-n1/stg-full-stack-app-backend/stg-backend-image
          docker build -t $IMAGE_NAME:staging-backend-v0.2 .
          docker push $IMAGE_NAME:staging-backend-v0.2

      - name: Deploy to Cloud Run
        run: |
          COMMIT_SHA=${{ github.sha }}
          gcloud run deploy stg-backend-v0.2 \
            --image asia-east1-docker.pkg.dev/peak-nimbus-466309-n1/stg-full-stack-app-backend/stg-backend-image:staging-backend-v0.2 \
            --region asia-east1 \
            --platform managed \
            --allow-unauthenticated \
            --project=peak-nimbus-466309-n1
